config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
	get 'events/reminders'
  resources :events

  get 'errors/not_found'

  get 'errors/internal_server_error'

  # crono jobs route
  mount Crono::Web, at: '/crono'

  # Building the questionnaire from web
  resources :questionnaires

  resources :invitations


#   do
#   collection do
#     get 'save_all_questionnaire_data', to: 'invitations#save_all_questionnaire_data', as: 'save_all_questionnaire_data'
#     # get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
#   end
# end
#




  resources :communications do
    collection do
      get 'lasts/:id', to: 'communications#lasts', as: 'lasts'
      get 'all/:id', to: 'communications#all', as: 'all'
    end
  end

  resources :activities do
    collection do
      get 'diets', to: 'activities#diets', as: 'diets'
      get 'physicals', to: 'activities#physicals', as: 'physicals'
      get 'mentals', to: 'activities#mentals', as: 'mentals'
      get 'medicinals', to: 'activities#medicinals', as: 'medicinals'
      get 'others', to: 'activities#others', as: 'others'
      get 'saveAllData', to: 'activities#saveAllData', as: 'saveAllData'
      get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
    end
  end

  resources :chats do
    collection do
      get 'chat/:id', to: 'chats#chat', as: 'chat'
      get 'chats/:id', to: 'chats#chats', as: 'chats'
    end
  end

  resources :plans do
    collection do
      post 'new/:u_id', to: 'plans#new', as: 'new'
      post 'deliver/:p_id', to: 'plans#deliver', as: 'deliver'
      post 'suspend/:p_id', to: 'plans#suspend', as: 'suspend'
      post 'stop/:p_id', to: 'plans#stop', as: 'stop'
    end
  end

  resources :users do
    collection do
      get 'plans/:id', to: 'users#plans', as: 'plans'
      get 'features/:id', to: 'users#features', as: 'features'
      get 'active_plans/:id', to: 'users#active_plans', as: 'active_plans'
      get 'suspended_plans/:id', to: 'users#suspended_plans', as: 'suspended_plans'
      get 'interrupted_plans/:id', to: 'users#interrupted_plans', as: 'interrupted_plans'
      get 'finished_plans/:id', to: 'users#finished_plans', as: 'finished_plans'
      get 'active'
      get 'archived'
      get 'suspended'
      get ':id/get_plans.pdfs', to: 'users#get_plans_pdf', as: 'get_plans_pdf'
      get ':id/get_feedbacks_to_do_pdf.pdfs', to: 'users#get_feedbacks_to_do_pdf', as: 'get_feedbacks_to_do_pdf'
      get ':id/get_charts_data', to: 'users#get_charts_data', as: 'get_charts_data'
      get 'get_scores', to: 'users#get_scores', as: 'get_scores'
      get 'get_images', to: 'users#get_images', as: 'get_images'
      get 'archive/:id', to: 'users#archive', as: 'archive'
      get 'restore/:id', to: 'users#restore', as: 'restore'

    end
  end

  resources :plannings do
    collection do
      post 'new/:p_id/:u_id', to: 'plannings#new', as: 'new'
      post 'assign/:p_id/:u_id/a_id', to: 'plannings#assign', as: 'assign'
      post 'dissociate/:a_id/:p_id/:u_id', to: 'activities#dissociate', as: 'dissociate'
      post 'destroy_all_schedules/:p_id', to: 'plannings#destroy_all_schedules', as: 'destroy_all_schedules'
    end
  end

  resources :schedules

  resources :questions do
    collection do
      get 'new/planning_id', to: 'questions#new', as: 'new'
    end
  end

  # pdfs
  get '/pdfs/user_plans_pdf', to: 'pdfs#user_plans_pdf', as: 'user_plans_pdf'

  get 'profile/index'
  # get 'static_pages/help'
  # get 'static_pages/about'

  devise_for :coach_users #, :controllers => {sessions: 'sessions'}
  get 'home/index'
  root 'home#index'

  resources :coach_users do
    collection do
      get 'coach_users/:id', to: 'coach_users#show', as: 'show'
    end
  end



  # Webhooks
  post '/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1' => 'webhooks#callback'

	# Wearable devices
	# Actions reserved for the coach:
	get 'wearables', to: 'wearables#index', as: 'wearables'
	get 'wearables/:id', to: 'wearables#show', as: 'show_wearable'
	get 'wearables/:id/monthly_report', to: 'wearables#monthly_report', as: 'monthly_report'
	get 'wearables/:id/weekly_chart', to: 'wearables#weekly_chart', as: 'weekly_chart'
	get 'wearables/:id/monthly_chart', to: 'wearables#monthly_chart', as: 'monthly_chart'
	get 'wearables/:id/edit', to: 'wearables#edit', as: 'edit_wearable'
	post 'wearables/:id/invite', to: 'wearables#invite', as: 'wearable_invite'
	post 'wearables/:id/disable', to: 'wearables#disable', as: 'wearable_disable'
	# Actions reserved for the user
	# starts fitbit oauth2 procedure
	get 'wearables/fitbit/connect/:token', to: 'wearables#connect', as: 'wearables_fitbit_connect'
	# oauth2 callback
	get 'users/auth/fitbit/callback', to: 'wearables#oauth2_callback'

	# User's objectives
	get 'objectives', to: 'objectives#index', as: 'objectives'
	get 'objectives/:id', to: 'objectives#show', as: 'user_objectives'
	get 'objectives/:id/new', to: 'objectives#new', as: 'new_user_objective'
	post 'objectives/:id/create', to: 'objectives#create', as: 'create_user_objective'
	get 'objectives/details/:id', to: 'objectives#details', as: 'objective_details'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


end

app/models/campaign.rb
class Campaign < ApplicationRecord
  has_many :invitations
  has_many :users, :through => :invitations
  has_many :questionnaires, :through => :invitations
  acts_as_taggable
end

app/controllers/users_controller.rb
require './lib/modules/chart_data_binder'

class UsersController < ApplicationController
  before_action :authenticate_coach_user!
  respond_to :html, :js
  layout 'profile'
  ARCHIVED = 'ARCHIVED'
  REGISTERED = 'REGISTERED'

  def index
    @users = User.where('coach_user_id = ? AND state <> ?', current_coach_user.id, ARCHIVED)
    @users = @users.paginate(:page => params[:page], per_page: 12).order('created_at DESC')

    # @users = User.find(params[:id]).invitations.last.questionnaire.questionnaire_questions.last.options.last.score


    respond_to do |format|
      format.html
      format.csv {send_data @users.to_csv}
    end

  end

  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    user.state = REGISTERED
    if user.valid?
      user.save!
      create_command_data(user)
      current_coach_user.users << user
      features = assign_questionnaires user
      if features.nil?
        flash[:err] = "C'é stato un problema interno e l'utente non é stato inserito, riprova piú tardi!"
      else
        flash[:OK] = 'Utente inserito con successo!'
      end
    else
      flash[:err] = 'Utente non inserito!'
      flash[:errors] = user.errors.messages
    end
    redirect_to users_path
  end

  def show
    @user = User.find(params[:id])
    # @user = User.find(params[:id]).invitations


    respond_to do |format|
      format.html
      format.csv {send_data @user.to_csv}
    end

  end

  def features
    @user = User.find(params[:id])


  end

  #archived users
  def archived
    @users = User.where(:state => ARCHIVED)
  end

  def plans
    @user = User.find(params[:id])
  end

  def active_plans
    @user = User.find(params[:id])
    @plans = @user.plans.where(:delivered => 1)
  end

  def suspended_plans
    @user = User.find(params[:id])
    @plans = @user.plans.where(:delivered => 2)
  end

  def interrupted_plans
    @user = User.find(params[:id])
    @plans = @user.plans.where(:delivered => 3)
  end

  def finished_plans
    @user = User.find(params[:id])
    @plans = @user.plans.where(:delivered => 4)
  end


  def get_charts_data
    user = User.find(params[:id])
    data = ChartDataBinder.new.get_overview_data(user)
    render json: data, status: :ok
  end

  def get_plans_pdf
    user = User.find(params[:id])
    @plans = user.plans

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{user.first_name}-Plans",
               template: 'users/user_plans',
               show_as_html: params.key?('debug'),
               dpi: '250',
               # orientation: 'Landscape',
               viewport: '1280x1024',
               footer: {right: '[page] of [topage]'}
      end
    end
  end

  def get_feedbacks_to_do_pdf
    @plans = Plan.joins(plannings: :notifications).where('notifications.date<=? AND notifications.done=? AND plans.delivered=? AND plans.user_id=?', Date.today, 0, 1, params[:id]).uniq
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "#{@plans[0].user.first_name}-Plans",
               template: 'users/user_feedbacks',
               show_as_html: params.key?('debug'),
               dpi: '250',
               # orientation: 'Landscape',
               viewport: '1280x1024',
               footer: {right: '[page] of [topage]'}
      end
    end
  end

  def get_scores
    data = ChartDataBinder.new.get_scores(current_coach_user)
    render json: data, status: :ok
  end

  def get_images
    data = ChartDataBinder.new.get_images(current_coach_user)
    render json: data, status: :ok
  end

  def archive
    user = User.find(params[:id])
    user.state = ARCHIVED
    user.save!
    flash[:OK] = 'Utente ARCHIVIATO con successo!'
    redirect_to users_path
  end

  def restore #from archived
    user = User.find(params[:id])
    user.state = REGISTERED
    user.save!
    flash[:OK] = 'Utente RIATTIVATO con successo!'
    redirect_to users_path
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:OK] = 'Utente ELIMINATO con successo!'
    redirect_to users_path
  end


  # Download data into csv
  # def saveAllData
  #   csv = UserExport.allData.to_csv.string
  #   send_data(csv,
  #             filename: 'allData.csv',
  #             type: 'text/csv',
  #             disposition: 'attachment')
  # end


  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :cellphone, :age, :patient_objective, :gender,
                                 :height, :weight, :blood_type, :tag_list)
    end

=begin
  def assign_questionnaires(user)
    (params[:questionnaires_ids] || []).each do |id|
      questionnaire = Questionnaire.find(id)
      if Questionnaire.where(initial: false)
        Invitation.create(user: user, questionnaire: questionnaire, completed: false)
      else
        Questionnaire.where(initial: true).each do |questionnaire|
          Invitation.create(user: user, questionnaire: questionnaire, completed: false)
        end
      end
    end
  end
=end

  def assign_questionnaires(user)
    (params[:questionnaires_ids] || []).each do |id|

      Invitation.create(user: user, questionnaire_id: id, completed: false)

    end
  end

  def create_command_data(user)
    BotCommand.create(data: {}.to_json, user: user)
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def ita_feedbacks_from_n(notification)
    planning = notification.planning
    activity = planning.activity
    case activity.a_type
      when '0'
        if planning.schedules.empty?
          "Il giorno #{notification.date.strftime('%d.%m.%Y')} per #{activity.n_times} volte."
        else
          "Il giorno #{notification.date.strftime('%d.%m.%Y')} alle ore #{notification.time.strftime('%H:%M')}."
        end
      when '1'
        if planning.schedules.empty?
          week, turn = week_and_order('week', planning.plan, planning, notification)
          "Per la #{turn} volta durante la #{week} settimana."
        else
          "Il giorno #{notification.date.strftime('%d.%m.%Y')} alle ore #{notification.time.strftime('%H:%M')}."
        end
      else
        if planning.schedules.empty?
          month, turn = week_and_order('month', planning.plan, planning, notification)
          "Per la #{turn} volta durante il #{month} mese."
        else
          "Il giorno #{notification.date.strftime('%d.%m.%Y')} alle ore #{notification.time.strftime('%H:%M')}."
        end

    end
  end

  def week_and_order(by, plan, planning, notification)
    # looping through months
    date = notification.date
    from = plan.from_day
    to = plan.to_day
    interval = by
    start = from
    week_number = 1
    while start < to
      stop  = start.send("end_of_#{interval}")
      if stop > to
        stop = to
      end

      interval_start = Date.parse(start.inspect)
      interval_end = Date.parse(stop.inspect)
      if interval_start<=date && interval_end>=date
        return week_number, Notification.where('planning_id = (?) AND date >= (?) AND date <= (?)', planning.id, interval_start, interval_end).index(notification)+1
      end

      start = stop.send("beginning_of_#{interval}")
      start += 1.send(interval)
      week_number = week_number + 1
    end
  end

  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end

  def delivered?(plan)
    case plan.delivered
      when 0
        'mdl-card__title'
      when 1
        'mdl-card__title2'
      when 2
        'mdl-card__title3'
      else
        'mdl-card__title4'
    end
  end

  def ita_category(cat)
    case cat
      when '0', 0
        'Dieta'
      when '1', 1
        'Attivita\' Fisica'
      when '2', 2
        'Benessere Mentale'
      when '3', 3
        'Medicina'
      else
        'Altro'
    end
  end

  def ita_a_type(a_type)
    case a_type
      when 0, '0'
        'Giorno'
      when 1, '1'
        'Settimana'
      else
        'Mese'
    end
  end

  def ita_schedule(schedule)
    ita_text = ''
    unless schedule.date.nil?
      ita_text += "Data: #{schedule.date.strftime('%d.%m.%Y')} "
    end
    unless schedule.day.nil?
      ita_text += "Giorno: #{ita_day(schedule.day)} "
    end
    unless schedule.time.nil?
      ita_text += "Ora: #{schedule.time.strftime('%H:%M')} "
    end
    ita_text
  end

  def ita_day(day)
    case day
      when 0
        'Lunedi'
      when 1
        'Martedi'
      when 2
        'Mercoledi'
      when 3
        'Giovedi'
      when 4
        'Venerdi'
      when 5
        'Sabato'
      else
        'Domenica'
    end
  end

  def pdf_activity_img(category)
    case category
      when '0'
        'diet.png'
      when '1'
        'fitness.png'
      when '2'
        'mental.png'
      when '3'
        'medicine.png'
      else
        'coffee.png'
    end
  end

end

app/views/users/_archived.html.erb
<% if @users.empty? %>
  <br>
  <div id="no-info-grid" class="mdl-grid">
    <div class="mdl-cell--12-col-desktop mdl-cell--8-col-tablet mdl-cell--4-col-phone">
      <div id="no-info-card" class="mdl-card mdl-shadow--4dp">
        <div class="mdl-card__title mdl-card--expand">
          <h2 class="mdl-card__title-text"> Nessuna paziente archivato </h2>
        </div>
        <div id="feature-card-supporting-text" class="mdl-card__supporting-text">

          Non hai ancora archiviato nessun paziente. I pazienti si possono archiviare cliccando sull'icona
          'raccoglitore' presente in alto a destra sulla card del paziente.

        </div>
      </div>
    </div>

  </div>
<% end %>

<div class="row">
  <div class="container">
    <% @users.each do |user| %>
      <%= cell(:user, user) %>
    <% end %>
  </div>
</div>

app/views/users/_index.html.erb
<% provide(:sub_title, 'Patients') %>

<div>
  <%= render 'users/users_header' %>

  <div id="patients">
    <div class="mdl-grid" >

      <% if @users.empty? %>
          <div class="mdl-cell--12-col-desktop mdl-cell--12-col-tablet mdl-cell--12-col-phone mdl-card mdl-shadow--2dp">
            <h2>
              Non e' presente nessun paziente per il momento.
              Inserisci un nuovo paziente attraverso il bottone in alto a destra.
            </h2>
          </div>
      <% end %>

      <% @users.each do |user|  %>
          <div class="active-patient-card patient-card mdl-cell--3-col-desktop mdl-cell--6-col-tablet mdl-cell--12-col-phone mdl-card mdl-shadow--2dp">
            <div class="mdl-card__media">
              <%= image_tag 'patient-conn.jpg', alt: 'paziente' %>
            </div>
            <div class="mdl-card__title mdl-card--expand">
              <h2 class="mdl-card__title-text"> <%= user.first_name %> <%= user.last_name %> </h2>
            </div>
            <div class="mdl-card__supporting-text">
              Dati sul Utente
            </div>
            <div class="mdl-card__actions mdl-card--border">
              <%= link_to 'Vedi Pagina Utente', user_path(user), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %>
            </div>

          </div>
      <% end %>

    </div>
  </div>

</div>

app/views/users/_plans.html.erb
<!-- Just include plans cell -->
<%= cell(:user_plans, @user, plans: @plans) %>

app/views/users/active_plans.js.erb
$('document').ready(function() {
    $('#users_plans').empty().html("<%= escape_javascript(render 'users/plans') %>")
    document.getElementById('active_plans_users').style.backgroundColor = '#757575'
});active_plans

app/views/users/archived.js.erb
$('document').ready(function() {
    $('#patients').empty().html("<%= escape_javascript(render 'users/archived') %>")

    $('#all-users').css('background', 'rgba(158, 158, 158, 0.2)')
    $('#archived-users').css('background', '#757575')

    $('#new_assign-user-notice').html('Utente ARCHIVIATO con successo!')

    Tipped.create('.delete-user', 'Cancella il Paziente per sempre');
    Tipped.create('.restore-user', 'Riattiva il Paziente');
});

app/views/users/create.js.erb
$('document').ready(function() {
    $('#patients-content').empty().html("<%= escape_javascript(render 'users/show') %>")

    $('#overview-user').css('background', 'white')
    $('#activities-user').css('background', 'rgba(158, 158, 158, 0.2)')
    $('#notifications-users').css('background', 'rgba(158, 158, 158, 0.2)')
    
    $('#new_assign-user-notice').html('Utente INSERITO con successo!')
});

app/views/users/index.html.erb
<%= provide(:title, "Lista Pazienti") %>
<div>
  <%= cell(:users_index_menu, current_coach_user) %>
  <div id="patients">
    <div class="users-index"></div>
    <% if @users.empty? %>
      <br>




      <div class="row">


        <div class="column container">


          <br>
          <div class="card">
            <div class="thumb_image"></div>
<!--            <img src="/images/activities.jpg" alt="CoachAI" style="width:100%">-->
            <div class="container">
              <h2><i class="material-icons md-36">weekend</i> Nessun Paziente registrato</h2>

              <p>Nell'archivio non e' presente nessun paziente per il momento. Inserisci un nuovo paziente attraverso il
                bottone verde in basso a destra.</p>

              <p><br>
                <%= link_to new_user_path, class: 'mdl-navigation__link' do %>
                  <button id="new-users" class="button">
                    <i class="material-icons">create</i>  Nuovo Paziente

                  </button>
                <% end %>

              </p>
            </div>
          </div>
        </div>

      </div>

    <% end %>
    <div class="mdl-grid mdl-cell--3-col">
      <div class="mdl-layout-spacer"></div>
      <div class="mdl-cell">
        <!-- add content here -->
      </div>
      <div class="mdl-cell middle_align col-lg-offset-3">
        <% if @users.exists? %>
        <%= link_to new_user_path, class: 'mdl-navigation__link' do %>
          <button id="new-users" class="btn btn-success btn-lg">
            <i class="material-icons">create</i> &nbsp Nuovo Paziente

          </button>
        <% end %>

          <%= link_to users_path(format: :csv), class: 'mdl-navigation__link' do %>
            <button class="btn btn-info btn-lg">
              <i class="material-icons">vertical_align_bottom</i> &nbsp scarica i dati degli utenti
            </button>
          <% end %>
        <% end %>


        <!-- also here -->
      </div>
      <div class="mdl-cell">
        <!-- and probably also here -->
      </div>
      <div class="mdl-layout-spacer"></div>
    </div>

    <div class="row user_pic_align">
      <div class="container">
        <% @users.each do |user| %>
          <%= cell(:user, user) %>
        <% end %>


      </div>
    </div>


  </div>
  <div class="mdl-grid mdl-cell--3-col">

    <%= will_paginate @users, renderer: BootstrapPagination::Rails %>
  </div>

</div>

app/views/users/new.html.erb
<%= provide(:title, "Registra Paziente") %>
<% provide(:sub_title, 'Nuovo Paziente') %>
  <div class="main-panel">
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8">
            <div class="card">
              <div class="card-header patient_profile" >
                <h4 class="title">Inserisci qui i dati del nuovo paziente</h4>
                <p class="category">Registrazione del profilo del paziente</p>
              </div>
              <div class="card-content">

                <div id="new-user-notice" class="notice"></div>
                Tutti i campi sono obbligatori!
                <div class="insert-error-msg"><%= yield(:insert_error_msg) %></div>
                <%= form_for @user, url: users_path, method: 'post' do |f| %>

                  <div id="name">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <i class="material-icons">hdr_weak</i>
                      <%= f.text_field :last_name, class: 'mdl-textfield__input', placeholder: 'Nome' %>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <i class="material-icons">hdr_strong</i>
                      <%= f.text_field :first_name, class: 'mdl-textfield__input', placeholder: 'Cognome'%>
                    </div>
                  </div>

                  <div id="name">
                    <div id="age">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <i class="material-icons">cake</i>
                        <%= f.number_field :age, class: 'mdl-textfield__input', pattern: '-?[0-9]*(\.[0-9]+)?', placeholder: 'Etá' %>
                        <span class="mdl-textfield__error">Deve essere formato da numeri e non lettere!</span>
                      </div>
                    </div>

                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <i class="material-icons">edit_location</i>
                      <%= f.text_field :patient_objective, class: 'mdl-textfield__input', placeholder: 'Obiettivo' %>
                    </div>
                  </div>

                  <div id="name">
                    <div id="phone">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <i class="material-icons">phonelink_ring</i>
                        <%= f.text_field :cellphone, class: 'mdl-textfield__input', pattern: '-?[0-9]*(\.[0-9]+)?', placeholder: 'Numero cell (solo numeri)' %>
                        <span class="mdl-textfield__error">Deve essere formato da numeri e non lettere!</span>
                      </div>
                    </div>

                    <div id="email">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <i class="material-icons">email</i>
                        <%= f.text_field :email, class: 'mdl-textfield__input', type: 'email', placeholder: 'Email (Es. user@example.com)' %>
                        <span class="mdl-textfield__error">Inserire un indirizzo email valido!</span>
                      </div>
                    </div>
                  </div>
                  <div id="name">
                    <div id="height">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <%= f.label :height, 'Altezza*' %><br>
                        <%= f.number_field :height, in: 0..200, step: 0.1 %>
                      </div>
                    </div>

                    <div id="weight">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <%= f.label :weight, 'Peso*' %><br>
                        <%= f.number_field :weight, in: 0..300, step: 0.5 %>
                      </div>
                    </div>
                  </div>

                  <div id="name">
                    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                      <i class="material-icons">wc</i>
                      <%= f.select(:gender) do %>
                        <% [['Maschio', 'maschio'], ['Femmina', 'femmina']].each do |c| -%>
                          <%= content_tag(:option, c.first, value: c.last) %>
                        <% end %>
                      <% end %>
                    </div>


                    <div id="blood_type">
                      <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                        <i class="material-icons">add_location</i>
                        <%= f.select(:blood_type) do %>
                          <% [['O Negativo', 'o negativo'], ['O Positivo', 'o positivo'], ['A Negativo', 'a negativo'], ['A Positivo', 'a positivo'], ['B Negativo', 'b negativo'], ['B Positivo', 'b positivo'], ['AB Negativo', 'ab negativo'], ['AB Positivo', 'ab positivo'],].each do |c| -%>
                            <%= content_tag(:option, c.first, value: c.last) %>
                          <% end %>
                        <% end %>
                      </div>
                    </div>
                  </div>

<hr>
                  <div id ="contact">

                    <div role="alert">
                      Ad ogni nuovo paziente puoi associare dei TAG scegliendoli dalla lista sottostante oppure inventandotene di nuovi.
                    </div>
                    <!-- Ignore this shitty style in view! -->
                    <ul style="clear: both; display: block; content: '';">
                      <% if ActsAsTaggableOn::Tag.count == 0 %>
                        <li class="list-group-item list-group-item-success" >Non sono ancora presenti TAG nel sistema. Inizia ad inserirne con questo nuovo paziente.</li>
                      <% else %>
                        <% ActsAsTaggableOn::Tag.all.each do |tag| %>
                          <li class="btn btn-success btn-group-sm btn-round" style="float: left; margin-right: 7px; margin-bottom: 7px;"><%= tag.name %></li>
                        <% end %>
                      <% end %>
                    </ul>

                    <br>
                    <div class="form-group">
                      <%= f.text_field :tag_list, class: 'form-control', placeholder: 'Inserisci qui i TAG separati da virgola', value: @user.tag_list.to_s %>
                    </div>

                    <%#= f.collection_check_boxes :questionnaire_ids, Questionnaire.all, :id, :title %>






                    <div class="questionnaires-list">
                      <!------ Include the above in your HEAD tag ---------->

                      <main class="container pt-5 list-group">
                        <div class="card mb-5">
                          <div class="card-header">Questionari</div>
                          <div class="card-block p-0">
                            <table class="table table-bordered table-sm m-0">
                              <thead class="">
                              <tr>
                                <th>#</th>
                                <th>Nome</th>
                                <!--                                  <th>Description</th>-->
                                <th>Creato</th>

                              </tr>
                              </thead>
                              <tbody>
                              <% Questionnaire.all.each do |questionnaire| %>
                                <tr>
                                  <td>
                                    <label class="custom-control custom-checkbox ">


                                      <%= check_box_tag "questionnaires_ids[]", questionnaire.id, inline_label: questionnaire.title, type: "checkbox", class: "custom-control-indicator custom-control-input" %>

                                    </label>
                                  </td>
                                  <td>  <%= questionnaire.title %> </td>

                                  <!--                                  <td><%#= questionnaire.desc %></td>-->
                                  <td><%= questionnaire.created_at.strftime("%D") %></td>

                                </tr>
                              <% end %>

                              </tbody>
                            </table>
                          </div>

                        </div>
                      </main>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary btn-large pull-right"><i class="material-icons">add</i> &nbsp Inserire Profilo</button>
                  <div class="clearfix"></div>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

  </div>

<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">