config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
	get 'events/reminders'
  resources :events

  get 'errors/not_found'

  get 'errors/internal_server_error'

  # crono jobs route
  mount Crono::Web, at: '/crono'

  # Building the questionnaire from web
  resources :questionnaires

  resources :invitations


#   do
#   collection do
#     get 'save_all_questionnaire_data', to: 'invitations#save_all_questionnaire_data', as: 'save_all_questionnaire_data'
#     # get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
#   end
# end
#




  resources :communications do
    collection do
      get 'lasts/:id', to: 'communications#lasts', as: 'lasts'
      get 'all/:id', to: 'communications#all', as: 'all'
    end
  end

  resources :activities do
    collection do
      get 'diets', to: 'activities#diets', as: 'diets'
      get 'physicals', to: 'activities#physicals', as: 'physicals'
      get 'mentals', to: 'activities#mentals', as: 'mentals'
      get 'medicinals', to: 'activities#medicinals', as: 'medicinals'
      get 'others', to: 'activities#others', as: 'others'
      get 'saveAllData', to: 'activities#saveAllData', as: 'saveAllData'
      get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
    end
  end

  resources :chats do
    collection do
      get 'chat/:id', to: 'chats#chat', as: 'chat'
      get 'chats/:id', to: 'chats#chats', as: 'chats'
    end
  end

  resources :plans do
    collection do
      post 'new/:u_id', to: 'plans#new', as: 'new'
      post 'deliver/:p_id', to: 'plans#deliver', as: 'deliver'
      post 'suspend/:p_id', to: 'plans#suspend', as: 'suspend'
      post 'stop/:p_id', to: 'plans#stop', as: 'stop'
    end
  end

  resources :users do
    collection do
      get 'plans/:id', to: 'users#plans', as: 'plans'
      get 'features/:id', to: 'users#features', as: 'features'
      get 'active_plans/:id', to: 'users#active_plans', as: 'active_plans'
      get 'suspended_plans/:id', to: 'users#suspended_plans', as: 'suspended_plans'
      get 'interrupted_plans/:id', to: 'users#interrupted_plans', as: 'interrupted_plans'
      get 'finished_plans/:id', to: 'users#finished_plans', as: 'finished_plans'
      get 'active'
      get 'archived'
      get 'suspended'
      get ':id/get_plans.pdfs', to: 'users#get_plans_pdf', as: 'get_plans_pdf'
      get ':id/get_feedbacks_to_do_pdf.pdfs', to: 'users#get_feedbacks_to_do_pdf', as: 'get_feedbacks_to_do_pdf'
      get ':id/get_charts_data', to: 'users#get_charts_data', as: 'get_charts_data'
      get 'get_scores', to: 'users#get_scores', as: 'get_scores'
      get 'get_images', to: 'users#get_images', as: 'get_images'
      get 'archive/:id', to: 'users#archive', as: 'archive'
      get 'restore/:id', to: 'users#restore', as: 'restore'

    end
  end

  resources :plannings do
    collection do
      post 'new/:p_id/:u_id', to: 'plannings#new', as: 'new'
      post 'assign/:p_id/:u_id/a_id', to: 'plannings#assign', as: 'assign'
      post 'dissociate/:a_id/:p_id/:u_id', to: 'activities#dissociate', as: 'dissociate'
      post 'destroy_all_schedules/:p_id', to: 'plannings#destroy_all_schedules', as: 'destroy_all_schedules'
    end
  end

  resources :schedules

  resources :questions do
    collection do
      get 'new/planning_id', to: 'questions#new', as: 'new'
    end
  end

  # pdfs
  get '/pdfs/user_plans_pdf', to: 'pdfs#user_plans_pdf', as: 'user_plans_pdf'

  get 'profile/index'
  # get 'static_pages/help'
  # get 'static_pages/about'

  devise_for :coach_users #, :controllers => {sessions: 'sessions'}
  get 'home/index'
  root 'home#index'

  resources :coach_users do
    collection do
      get 'coach_users/:id', to: 'coach_users#show', as: 'show'
    end
  end



  # Webhooks
  post '/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1' => 'webhooks#callback'

	# Wearable devices
	# Actions reserved for the coach:
	get 'wearables', to: 'wearables#index', as: 'wearables'
	get 'wearables/:id', to: 'wearables#show', as: 'show_wearable'
	get 'wearables/:id/monthly_report', to: 'wearables#monthly_report', as: 'monthly_report'
	get 'wearables/:id/weekly_chart', to: 'wearables#weekly_chart', as: 'weekly_chart'
	get 'wearables/:id/monthly_chart', to: 'wearables#monthly_chart', as: 'monthly_chart'
	get 'wearables/:id/edit', to: 'wearables#edit', as: 'edit_wearable'
	post 'wearables/:id/invite', to: 'wearables#invite', as: 'wearable_invite'
	post 'wearables/:id/disable', to: 'wearables#disable', as: 'wearable_disable'
	# Actions reserved for the user
	# starts fitbit oauth2 procedure
	get 'wearables/fitbit/connect/:token', to: 'wearables#connect', as: 'wearables_fitbit_connect'
	# oauth2 callback
	get 'users/auth/fitbit/callback', to: 'wearables#oauth2_callback'

	# User's objectives
	get 'objectives', to: 'objectives#index', as: 'objectives'
	get 'objectives/:id', to: 'objectives#show', as: 'user_objectives'
	get 'objectives/:id/new', to: 'objectives#new', as: 'new_user_objective'
	post 'objectives/:id/create', to: 'objectives#create', as: 'create_user_objective'
	get 'objectives/details/:id', to: 'objectives#details', as: 'objective_details'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_login_form.erb
<div class="section">
  <div class="container text-center">
    <div class="row">
      <div class="col-md-8 col-md-offset-2 text-center">
        <h2>CoachAI</h2>
        <h4>Pannello di login</h4>
      </div>
    </div>
  </div>
</div>
<%= devise_error_messages! %>
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="section section-full-screen section-signup miniback">
    <div class="container">
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <div class="card card-signup login_card">
            <form class="form" method="" action="">
              <div class="header header-primary text-center">
                <h2>CoachAI</h2>
                <h4>Pannello di login</h4>

              </div>
              <p class="text-divider">Tutti i campi richiesti *</p>
              <div class="content">

                <!--<div class="input-group login_group">-->
                <!--<span class="input-group-addon">-->
                <!--<i class="material-icons">face</i>-->
                <!--</span>-->
                <!--<input type="text" class="form-control" placeholder="Nome, Cognome...">-->
                <!--</div>-->

                <div class="input-group login_group">
										<span class="input-group-addon">
											<i class="material-icons">email</i>
										</span>
                  <%= f.email_field :email, autofocus: true, class: 'mdl-textfield__input form-control', placeholder: 'Email...',
                                    for: 'login' %>
                </div>

                <div class="input-group login_group">
										<span class="input-group-addon">
											<i class="material-icons">lock_outline</i>
										</span>

                  <%= f.password_field :password, autofocus: true, autocomplete: 'off', class: 'mdl-textfield__input form-control',
                                       placeholder: 'Password...', for: 'password' %>
                </div>
                <!--<div class="input-group login_group">-->
										<!--<span class="input-group-addon">-->
									<!--<i class="material-icons">vpn_key</i>-->
										<!--</span>-->
                  <!--<#%= f.text_field :access_code, class: 'mdl-textfield__input form-control', placeholder: 'Codice
                   d\'accesso...', for: 'login' %>-->
                <!--</div>-->

                <% if devise_mapping.rememberable? %>
                  <div class=" field checkme login_group">
                    <%= f.check_box :remember_me %>
                    <%= f.label 'Ricordati di me' %>
                  </div>

                <% end %>

                <!-- If you want to add a checkbox to this form, uncomment this code
                <div class="checkbox">
                  <label>
                    <input type="checkbox" name="optionsCheckboxes" checked>
                    Subscribe to newsletter
                  </label>
                </div> -->
              </div>
              <div class="footer text-center">
                <%= f.submit "Log in", class: 'btn btn-success btn-lg' %>
              </div>
              <div class="col-md-12 text-center">
                <p>Non hai un account? <a> <%= link_to "Iscriviti qui", new_coach_user_registration_path, class: "btn
              btn-info btn-sm" %></a></p>
              </div>
            </form>
          </div>

        </div>
      </div>
    </div>
  </div>

  <div class="mdl-grid">
    <div class="mdl-cell mdl-cell--12-col">
      <div class="mdl-color-text--primary" style="float: right">
        <%= render "devise/shared/links" %>
      </div>
    </div>
  </div>

<% end %>

app/views/home/index.html.erb
<% provide(:title, 'Home') %>
<div class="wrapper">
  <div class="page-header section-dark">
    <div class="filter"></div>
    <div class="content-center">
      <div class="container">
      </div>
    </div>
  </div>
</div>
<div class="btn-banner">
  <div class="section">

  <% if coach_user_signed_in? %>
      <%= link_to profile_index_path, class: 'mdl-navigation__link' do %>
        <button  class="button main_button">
          <i class="material-icons">chat</i> Accesso Dashboard
        </button>
      <% end %>
  <% else %>
      <button class="button" id="btn_login_1">
        <span><a  data-toggle="tab" class="main_button"><i class="material-icons">chat</i> Accesso CoachAI</a></span>
      </button>
    <!--</button>-->
    <!-- Element to pop up -->
    <div id="login_pop_up">
      <%= render 'home/login_form' %>
    </div>
  <% end %>
</div>

</div>
<div class="section section-tabs home_bottom">
  <div class="container">

      <div class="col-md-12">
        <div class="title">
          <h3>Perche usare gli agenti conversazionali:</h3>
        </div>

        <!-- Tabs with icons on Card -->
        <div class="card card-nav-tabs">
          <div class="header header-success">
            <!-- colors: "header-primary", "header-info", "header-success", "header-warning", "header-danger" -->
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs">
                  <li class="active">
                    <a href="#profile" data-toggle="tab">
                      <i class="material-icons">games</i>
                     Il Chatbot e Assistenza Sanitaria
                    </a>
                  </li>
                  <li>
                    <a href="#messages" data-toggle="tab">
                      <i class="material-icons">face</i>
                     Il Chatbot e Medici
                    </a>
                  </li>
                  <li>
                    <a href="#settings" data-toggle="tab">
                      <i class="material-icons">supervisor_account</i>
                      Il Chatbot e Pazienti
                    </a>

                  </li>
                  <li>
                    <a href="#new_platform" data-toggle="tab">
                      <i class="material-icons">format_quote</i>
                      La Nuova Visione

                    </a>

                  </li>
                </ul>
              </div>
            </div>
          </div>
          <div class="content">
            <div class="tab-content text-center">

              <div class="tab-pane active" id="profile">
                <div class="mdl-card__media">
                  <%= image_tag 'CoachAI Graphics/im2.png' %>
                </div>
                <p> Con l'aumento dei costi sanitari, l'attenzione attuale ha spostato le preferenze individuali dal trattamento delle malattie alla prevenzione. Le attuali applicazioni di telemedicina per la prevenzione delle malattie e la promozione dello stile di vita si concentrano sulla gestione delle condizioni del paziente e sulla raccomandazione di attività e piani per migliorare le loro condizioni. La ricerca della salute digitale per ottimizzare l'esperienza di coinvolgimento dei pazienti e il processo di interazione e supporto ai pazienti trarranno maggior beneficio dai sistemi di chatbot, specialmente dopo la dimissione ospedaliera. Ciò offre la possibilità di semplificare la comunicazione tra medico e paziente tramite un'applicazione di telemedicina basata su chatbot. </p>
              </div>

              <div class="tab-pane" id="messages">
                <div class="mdl-card__media">
                  <%= image_tag 'CoachAI Graphics/im1.png' %>
                </div>
                <p> Gli agenti di conversazione possono supportare i medici gestendo compiti meno importanti, che i medici eseguono ripetutamente e che impedisce loro di concentrarsi su pazienti con condizioni più critiche. Detto questo, i medici svolgono un ruolo cruciale nel processo di cura fornendo il supporto necessario per il paziente. Pertanto, gli agenti di conversazione non possono mai sostituire i medici, tuttavia, possono agire come un assistente virtuale per aiutare i medici a concentrarsi su attività meno importanti ma importanti. Per aiutare i medici, il chatbot può dare peso alle condizioni del paziente, in base alla priorità e alla gravità (alto, moderato, basso o non necessario).</p>
              </div>

              <div class="tab-pane" id="settings">
                <div class="mdl-card__media">
                  <%= image_tag 'CoachAI Graphics/im3.png' %>
                </div>
                <p>Gli agenti di conversazione possono coprire il divario nell'interazione fisico-paziente automatizzando le attività, pianificando eventi e fornendo supporto 24/7 ai pazienti. Se definiti con cura, i chatbot possono ridurre il lavoro del medico e aiutarli a fornire interventi efficaci. Chatbots può gestire la prenotazione di un appuntamento con un medico o un ospedale, richiedendo informazioni semplici, fornendo informazioni sullo stato mentale, monitoraggio della dieta, attività fisica, sonno e benessere mentale.
                    Gli agenti di conversazione possono fornire diagnosi e monitoraggio della salute. Questo tipo di agenti conversazionali è avanzato e focalizzato sulla gestione e il controllo di una malattia. Considerando che, gli agenti di conversazione che tracciano il sonno, la dieta, l'attività fisica e lo stress sono per lo più focalizzati sulla promozione della salute e la prevenzione dall'escalation nella fase a rischio per una malattia.</p>
              </div>
              <div class="tab-pane" id="new_platform">
                <div class="mdl-card__media">
                  <%= image_tag 'CoachAI Graphics/bots.png' %>
                </div>
                <p>I più utilizzati per costruire gli agenti di conversazione si basano su uno o su una combinazione delle tecnologie di cui sopra. Per confermare la nostra analisi, abbiamo portato le nostre indagini a diventare più esperti. Oltre al focus tecnico, abbiamo studiato gli scopi e le funzionalità.</p>
              </div>
            </div>
          </div>
        </div>
        <!-- End Tabs with icons on Card -->

      </div>



    </div>

</div>