config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
	get 'events/reminders'
  resources :events

  get 'errors/not_found'

  get 'errors/internal_server_error'

  # crono jobs route
  mount Crono::Web, at: '/crono'

  # Building the questionnaire from web
  resources :questionnaires

  resources :invitations


#   do
#   collection do
#     get 'save_all_questionnaire_data', to: 'invitations#save_all_questionnaire_data', as: 'save_all_questionnaire_data'
#     # get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
#   end
# end
#




  resources :communications do
    collection do
      get 'lasts/:id', to: 'communications#lasts', as: 'lasts'
      get 'all/:id', to: 'communications#all', as: 'all'
    end
  end

  resources :activities do
    collection do
      get 'diets', to: 'activities#diets', as: 'diets'
      get 'physicals', to: 'activities#physicals', as: 'physicals'
      get 'mentals', to: 'activities#mentals', as: 'mentals'
      get 'medicinals', to: 'activities#medicinals', as: 'medicinals'
      get 'others', to: 'activities#others', as: 'others'
      get 'saveAllData', to: 'activities#saveAllData', as: 'saveAllData'
      get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
    end
  end

  resources :chats do
    collection do
      get 'chat/:id', to: 'chats#chat', as: 'chat'
      get 'chats/:id', to: 'chats#chats', as: 'chats'
    end
  end

  resources :plans do
    collection do
      post 'new/:u_id', to: 'plans#new', as: 'new'
      post 'deliver/:p_id', to: 'plans#deliver', as: 'deliver'
      post 'suspend/:p_id', to: 'plans#suspend', as: 'suspend'
      post 'stop/:p_id', to: 'plans#stop', as: 'stop'
    end
  end

  resources :users do
    collection do
      get 'plans/:id', to: 'users#plans', as: 'plans'
      get 'features/:id', to: 'users#features', as: 'features'
      get 'active_plans/:id', to: 'users#active_plans', as: 'active_plans'
      get 'suspended_plans/:id', to: 'users#suspended_plans', as: 'suspended_plans'
      get 'interrupted_plans/:id', to: 'users#interrupted_plans', as: 'interrupted_plans'
      get 'finished_plans/:id', to: 'users#finished_plans', as: 'finished_plans'
      get 'active'
      get 'archived'
      get 'suspended'
      get ':id/get_plans.pdfs', to: 'users#get_plans_pdf', as: 'get_plans_pdf'
      get ':id/get_feedbacks_to_do_pdf.pdfs', to: 'users#get_feedbacks_to_do_pdf', as: 'get_feedbacks_to_do_pdf'
      get ':id/get_charts_data', to: 'users#get_charts_data', as: 'get_charts_data'
      get 'get_scores', to: 'users#get_scores', as: 'get_scores'
      get 'get_images', to: 'users#get_images', as: 'get_images'
      get 'archive/:id', to: 'users#archive', as: 'archive'
      get 'restore/:id', to: 'users#restore', as: 'restore'

    end
  end

  resources :plannings do
    collection do
      post 'new/:p_id/:u_id', to: 'plannings#new', as: 'new'
      post 'assign/:p_id/:u_id/a_id', to: 'plannings#assign', as: 'assign'
      post 'dissociate/:a_id/:p_id/:u_id', to: 'activities#dissociate', as: 'dissociate'
      post 'destroy_all_schedules/:p_id', to: 'plannings#destroy_all_schedules', as: 'destroy_all_schedules'
    end
  end

  resources :schedules

  resources :questions do
    collection do
      get 'new/planning_id', to: 'questions#new', as: 'new'
    end
  end

  # pdfs
  get '/pdfs/user_plans_pdf', to: 'pdfs#user_plans_pdf', as: 'user_plans_pdf'

  get 'profile/index'
  # get 'static_pages/help'
  # get 'static_pages/about'

  devise_for :coach_users #, :controllers => {sessions: 'sessions'}
  get 'home/index'
  root 'home#index'

  resources :coach_users do
    collection do
      get 'coach_users/:id', to: 'coach_users#show', as: 'show'
    end
  end



  # Webhooks
  post '/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1' => 'webhooks#callback'

	# Wearable devices
	# Actions reserved for the coach:
	get 'wearables', to: 'wearables#index', as: 'wearables'
	get 'wearables/:id', to: 'wearables#show', as: 'show_wearable'
	get 'wearables/:id/monthly_report', to: 'wearables#monthly_report', as: 'monthly_report'
	get 'wearables/:id/weekly_chart', to: 'wearables#weekly_chart', as: 'weekly_chart'
	get 'wearables/:id/monthly_chart', to: 'wearables#monthly_chart', as: 'monthly_chart'
	get 'wearables/:id/edit', to: 'wearables#edit', as: 'edit_wearable'
	post 'wearables/:id/invite', to: 'wearables#invite', as: 'wearable_invite'
	post 'wearables/:id/disable', to: 'wearables#disable', as: 'wearable_disable'
	# Actions reserved for the user
	# starts fitbit oauth2 procedure
	get 'wearables/fitbit/connect/:token', to: 'wearables#connect', as: 'wearables_fitbit_connect'
	# oauth2 callback
	get 'users/auth/fitbit/callback', to: 'wearables#oauth2_callback'

	# User's objectives
	get 'objectives', to: 'objectives#index', as: 'objectives'
	get 'objectives/:id', to: 'objectives#show', as: 'user_objectives'
	get 'objectives/:id/new', to: 'objectives#new', as: 'new_user_objective'
	post 'objectives/:id/create', to: 'objectives#create', as: 'create_user_objective'
	get 'objectives/details/:id', to: 'objectives#details', as: 'objective_details'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


end

app/models/activity.rb
class Activity < ApplicationRecord
  validates_uniqueness_of :name, message: "Attivita' con lo stesso nome gia' presente nel sistema"
  validates :desc, presence: { message: 'Descrizione obbligatoria.' }
  validates :category, presence: { message: 'Categoria obbligatoria' }
  validates :a_type, presence: { message: 'Tipologia obbligatoria' }
  validates :n_times, presence: { message: 'Numero di volte obbligatoria' }

  belongs_to :coach_user, optional: false
  has_many :plannings, dependent: :destroy
  has_many :plans, :through => :plannings
  has_many :users, :through => :plans
end


# user.where(first_name"name").destroy rail s
#
# User.with_deleted.where(:activities.name=>"")

app/controllers/activities_controller.rb
require 'csv_data/user_export'

class ActivitiesController < ApplicationController

  layout 'profile'
  
  def show
    @activity = Activity.find(params[:id])
  
  
  end
  
  def index
    @activities = Activity.where(coach_user: current_coach_user)
  end
  
  def new
    @activity = Activity.new
  end
  
  def create
    activity = Activity.new activity_params
    activity.coach_user = current_coach_user
    if activity.save
      flash[:OK] = 'La tua attività è stata AGGIUNTA con successo!'
    else
      flash[:err] = "L'Attivita NON È STATA INSERITA"
      flash[:errors] = activity.errors.messages
    end
    redirect_to activities_path
  end
  
  def edit
  end
  
  def update
    activity = Activity.find(params[:id])
    if !activity.update(activity_params)
      flash[:OK] = "L'Attivita è stata modificata con successo!"
    else
      flash[:err] = "C'e' stato un problema durante l'aggiornamento dell'attivita'. La preghiamo di ricontrollare i dati inseriti e riprovare."
      flash[:errors] = activity.errors.messages
    end
    redirect_to activities_path
  end
  
  def destroy
    activity = Activity.find(params[:id])
    if activity.destroy
      flash[:OK] = 'La tua attivita\' e\' stata eliminata con successo!'
    else
      flash[:err] = "C'e' stato un problema durante la distruzione dell'attivita'. La preghiamo di riprovare piu' tardi."
      flash[:errors] = activity.errors.messages
    end
    redirect_to activities_path
  end
  
  def diets
    @activities = Activity.where(:category => 0, coach_user: current_coach_user)
  end
  
  def physicals
    @activities = Activity.where(:category => 1, coach_user: current_coach_user)
  end
  
  def mentals
    @activities = Activity.where(:category => 2, coach_user: current_coach_user)
  end
  
  def medicinals
    @activities = Activity.where(:category => 3, coach_user: current_coach_user)
  end
  
  def others
    @activities = Activity.where(:category => 4, coach_user: current_coach_user)
  end
  
  
  # Download data into csv
  def saveAllData
    
    csv = UserExport.allData.to_csv.string
    User.find_each do |user|
    csv << "\n Username: #{user.first_name} #{user.last_name} [User TAG: #{user.tag_list}]"
    end
    send_data(csv,
              filename: 'allData.csv',
              type: 'text/csv',
              disposition: 'attachment')
  end
  
  def saveUserData
    user = User.find(params[:id])
    csv = UserExport.userData(user).to_csv.string
    csv << "\n Username: #{user.first_name} #{user.last_name}[User TAG: #{user.tag_list}]"
    send_data(csv,
              filename: 'userData.csv',
              type: 'text/csv',
              disposition: 'attachment')
  end
  
  
  private
  
  def activity_params
    params.require(:activity).permit(:name, :desc, :a_type, :category, :n_times)
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def match_category(category)
    case category
      when '0'
        'Dieta'
      when '1'
        "Attivita' Fisica"
      when '2'
        'Benessere Mentale'
      when '3'
        'Medicina'
      else
        'Altro'
    end
  end

  def match_a_type(a_type)
    case a_type
      when '0'
        'Giornaliera'
      when '1'
        'Settimanale'
      else
        'Mensile'
    end
  end
end

app/views/activities/_all_in_table.html.erb
<table class="mdl-data-table mdl-js-data-table mdl-shadow--2dp">
  <thead>
  <tr>
    <th class="mdl-data-table__cell--non-numeric">Nome Attivita</th>
    <th>Categoria</th>
    <th>Tipologia</th>
    <th></th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @activities.each do |a| %>
      <tr>
        <td class="mdl-data-table__cell--non-numeric"> <b><%= a.name %></b> </td>
        <td> <%= match_category(a.category) %> </td>
        <td> <%= match_a_type(a.a_type) %> </td>
        <td><%= link_to 'Vedi', activity_path(a), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' %> </td>
        <td><%= link_to 'Elimina ', activity_path(a), method: 'delete',
                        data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\' potrebbe essere gia\' stata assegnata ad un paziente!!!'},
                        class: 'mdl-button mdl-button--accent mdl-js-button mdl-js-ripple-effect' %> </td>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/activities/_menu.html.erb
<header class="profile_content_header mdl-layout__header sub_menu_image">


    <nav class="mdl-navigation" >




        <div class="container">

          <!--  buttons -->


            <div class="row">
              <div class="col-md-10 ml-auto mr-auto">
                <%= link_to activities_path, class: 'mdl-navigation__link' do %>
                  <button id="activities-all" class="btn btn-primary btn-large button_attivi">
                    <i class="material-icons">featured_play_list</i> &nbsp Tutte
                  </button>
                <% end %>


                <%= link_to diets_activities_path,  class: 'mdl-navigation__link' do %>
                  <button id="activities-diets" class="btn btn-info btn-large button_diet">
                    <i class="material-icons">restaurant</i> &nbsp Diete
                  </button>
                <% end %>


                <%= link_to physicals_activities_path,   class: 'mdl-navigation__link' do %>
                  <button id="activities-physicals" class="btn btn-warning btn-large button_fisiche" >
                    <i class="material-icons">fitness_center</i> &nbsp Fisiche
                  </button>
                <% end %>

                <%= link_to mentals_activities_path, class: 'mdl-navigation__link' do %>
                  <button id="activities-mentals" class="btn btn-success btn-large button_mentale" >
                    <i class="material-icons">mood</i> &nbsp Benessere Mentale
                  </button>
                <% end %>

                <%= link_to medicinals_activities_path, class: 'mdl-navigation__link' do %>
                  <button id="activities-medicinals" class="btn btn-danger btn-large button_medicinali" >
                    <i class="material-icons">local_hospital</i> &nbsp Medicinali
                  </button>
                <% end %>

                <%= link_to others_activities_path, remote: true, class: 'mdl-navigation__link' do %>
                  <button id="activities-others" class="btn btn-default btn-large button_alt" >
                    <i class="material-icons">grain</i> &nbsp Altro
                  </button>
                <% end %>

              </div>
            </div>




          </div>

    </nav>

</header>

app/views/activities/diets.html.erb
<%= provide(:title, "Diete") %>
<div class="container">
<h2>Diete</h2>




  <div class="card-content">
  <div class="tab-content">
    <div class="tab-pane active" id="profile">
      <table class="table card-content content_align table-responsive table-hover">
        <thead class="text-warning">
        <th>Nome Attività</th>
        <th>Categoria</th>
        <th>Tipologia</th>
        <th>Modifica</th>
        <th>Elimina</th>
        </thead>
        <tbody>
        <% @activities.each do |a| %>
          <tr>
            <td><%= a.name %></td>
            <td> <%= match_category(a.category) %> </td>
            <td> <%= match_a_type(a.a_type) %> </td>
            <td> <%= link_to activity_path(a), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>
                <button class="btn btn-sm btn-success">
                  <i class="material-icons">important_devices</i> &nbsp Modifica
                </button>
              <% end %> </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                   potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button class="btn btn-sm btn-danger">
                  <i class="material-icons">delete</i> &nbsp Elimina
                </button>
              <% end %> </td>


            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
    <% @activities.each do |a| %>
      <div class="tab-pane " id="messages">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Categoria</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.category = "0" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "1" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "2" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "3" %>
                    <%= match_category(a.category) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>
                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.category) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td><%= link_to activity_path(a), method: 'delete',
                            data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>
          </tr>

          </tbody>
        </table>
      </div>
    <% end %>
    <% @activities.each do |a| %>
      <div class="tab-pane" id="settings">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Tipologia</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.a_type = "0" %>
                    <%= match_a_type(a.a_type) %>
                  <% elsif a.a_type = "1" %>
                    <%= match_a_type(a.a_type) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>

                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.a_type) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attività? L\'attività
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>

          </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/activities/index.html.erb
<%= provide(:title, "Lista Attivita'") %>
<%= render 'activities/menu' %>


<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="card">
      <div class="card-header card-chart" data-background-color="green">
        <div class="ct-chart" id="dailySalesChart"></div>
      </div>
      <div class="card-content">
        <h4 class="title">Qui sotto ci sono tutte le attivita presenti nel sistema</h4>

        <%= render 'activities/activities' %>
        <div class="mdl-layout-spacer"></div>

        <%= link_to new_activity_path, method: 'get' do %>
          <button id="activities-user" class="btn btn-info btn-large">
            <i class="material-icons">playlist_add</i> &nbsp Aggiungi Attivita
          </button>
        <% end %>
        <div class="mdl-layout-spacer"></div>
      </div>
      <div class="card-footer">
        <div class="stats">

          
        </div>
      </div>
    </div>
  </div>

</div>

app/views/activities/mentals.html.erb
<%= provide(:title, "Benessere Mentale") %>

<div class="container">
<h2>Benessere Mentale</h2>

<div class="card-content">
  <div class="tab-content">
    <div class="tab-pane active" id="profile">
      <table class="table card-content content_align table-responsive table-hover">
        <thead class="text-warning">
        <th>Nome Attività</th>
        <th>Categoria</th>
        <th>Tipologia</th>
        <th>Modifica</th>
        <th>Elimina</th>
        </thead>
        <tbody>
        <% @activities.each do |a| %>
          <tr>
            <td><%= a.name %></td>
            <td> <%= match_category(a.category) %> </td>
            <td> <%= match_a_type(a.a_type) %> </td>
            <td> <%= link_to activity_path(a), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>
                <button class="btn btn-sm btn-success">
                  <i class="material-icons">important_devices</i> &nbsp Modifica
                </button>
              <% end %> </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                   potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button class="btn btn-sm btn-danger">
                  <i class="material-icons">delete</i> &nbsp Elimina
                </button>
              <% end %> </td>


            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
    <% @activities.each do |a| %>
      <div class="tab-pane " id="messages">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Categoria</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.category = "0" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "1" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "2" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "3" %>
                    <%= match_category(a.category) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>
                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.category) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td><%= link_to activity_path(a), method: 'delete',
                            data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>
          </tr>

          </tbody>
        </table>
      </div>
    <% end %>
    <% @activities.each do |a| %>
      <div class="tab-pane" id="settings">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Tipologia</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.a_type = "0" %>
                    <%= match_a_type(a.a_type) %>
                  <% elsif a.a_type = "1" %>
                    <%= match_a_type(a.a_type) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>

                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.a_type) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attività? L\'attività
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>

          </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/activities/others.html.erb
<div class="container">
<h2>Altri</h2>

<div class="card-content">
  <div class="tab-content">
    <div class="tab-pane active" id="profile">
      <table class="table card-content content_align table-responsive table-hover">
        <thead class="text-warning">
        <th>Nome Attività</th>
        <th>Categoria</th>
        <th>Tipologia</th>
        <th>Modifica</th>
        <th>Elimina</th>
        </thead>
        <tbody>
        <% @activities.each do |a| %>
          <tr>
            <td><%= a.name %></td>
            <td> <%= match_category(a.category) %> </td>
            <td> <%= match_a_type(a.a_type) %> </td>
            <td> <%= link_to activity_path(a), class: 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' do %>
                <button class="btn btn-sm btn-success">
                  <i class="material-icons">important_devices</i> &nbsp Modifica
                </button>
              <% end %> </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                   potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button class="btn btn-sm btn-danger">
                  <i class="material-icons">delete</i> &nbsp Elimina
                </button>
              <% end %> </td>


            </td>
          </tr>
        <% end %>

        </tbody>
      </table>
    </div>
    <% @activities.each do |a| %>
      <div class="tab-pane " id="messages">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Categoria</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.category = "0" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "1" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "2" %>
                    <%= match_category(a.category) %>
                  <% elsif a.category = "3" %>
                    <%= match_category(a.category) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>
                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.category) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td><%= link_to activity_path(a), method: 'delete',
                            data: {confirm: 'Sei sicuro di voler eliminare l\'attivita\'? L\'attivita\'
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>
          </tr>

          </tbody>
        </table>
      </div>
    <% end %>
    <% @activities.each do |a| %>
      <div class="tab-pane" id="settings">
        <table class="table table-responsive table-hover content_align">
          <thead class="text-warning">

          <th>Tipologia</th>
          <th>Count</th>
          <th>Modifica</th>
          <th>Elimina</th>
          </thead>
          <tbody>
          <tr>
            <td>
              <div class="checkbox">
                <label>
                  <% if a.a_type = "0" %>
                    <%= match_a_type(a.a_type) %>
                  <% elsif a.a_type = "1" %>
                    <%= match_a_type(a.a_type) %>
                  <% else %>
                    <%= match_category(a.category) %>
                  <% end %>

                </label>
              </div>
            </td>
            <td>
              <button class="btn btn-info btn-fab btn-round">
                <%= Activity.count(a.a_type) %></button>
            </td>
            <td class="td-actions text-right">
              <%= link_to activity_path(a) do %>
                <button type="button" rel="tooltip" title="Modifica attività" class="btn btn-warning btn-fab btn-round">
                  <i class="material-icons">edit</i>
                </button>
              <% end %>

            </td>
            <td> <%= link_to activity_path(a), method: 'delete',
                             data: {confirm: 'Sei sicuro di voler eliminare l\'attività? L\'attività
                                                     potrebbe essere gia\' stata assegnata ad un paziente!'} do %>
                <button type="button" rel="tooltip" title="Elimina attività" class="btn btn-danger btn-fab btn-round">
                  <i class="material-icons">close</i>
                </button>
              <% end %></td>

          </tr>
          </tbody>
        </table>
      </div>
    <% end %>
  </div>
</div>
</div>