config/routes.rb
Rails.application.routes.draw do
  get 'calendar/index'
	get 'events/reminders'
  resources :events

  get 'errors/not_found'

  get 'errors/internal_server_error'

  # crono jobs route
  mount Crono::Web, at: '/crono'

  # Building the questionnaire from web
  resources :questionnaires

  resources :invitations


#   do
#   collection do
#     get 'save_all_questionnaire_data', to: 'invitations#save_all_questionnaire_data', as: 'save_all_questionnaire_data'
#     # get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
#   end
# end
#




  resources :communications do
    collection do
      get 'lasts/:id', to: 'communications#lasts', as: 'lasts'
      get 'all/:id', to: 'communications#all', as: 'all'
    end
  end

  resources :activities do
    collection do
      get 'diets', to: 'activities#diets', as: 'diets'
      get 'physicals', to: 'activities#physicals', as: 'physicals'
      get 'mentals', to: 'activities#mentals', as: 'mentals'
      get 'medicinals', to: 'activities#medicinals', as: 'medicinals'
      get 'others', to: 'activities#others', as: 'others'
      get 'saveAllData', to: 'activities#saveAllData', as: 'saveAllData'
      get 'saveUserData/:id', to: 'activities#saveUserData', as: 'saveUserData'
    end
  end

  resources :chats do
    collection do
      get 'chat/:id', to: 'chats#chat', as: 'chat'
      get 'chats/:id', to: 'chats#chats', as: 'chats'
    end
  end

  resources :plans do
    collection do
      post 'new/:u_id', to: 'plans#new', as: 'new'
      post 'deliver/:p_id', to: 'plans#deliver', as: 'deliver'
      post 'suspend/:p_id', to: 'plans#suspend', as: 'suspend'
      post 'stop/:p_id', to: 'plans#stop', as: 'stop'
    end
  end

  resources :users do
    collection do
      get 'plans/:id', to: 'users#plans', as: 'plans'
      get 'features/:id', to: 'users#features', as: 'features'
      get 'active_plans/:id', to: 'users#active_plans', as: 'active_plans'
      get 'suspended_plans/:id', to: 'users#suspended_plans', as: 'suspended_plans'
      get 'interrupted_plans/:id', to: 'users#interrupted_plans', as: 'interrupted_plans'
      get 'finished_plans/:id', to: 'users#finished_plans', as: 'finished_plans'
      get 'active'
      get 'archived'
      get 'suspended'
      get ':id/get_plans.pdfs', to: 'users#get_plans_pdf', as: 'get_plans_pdf'
      get ':id/get_feedbacks_to_do_pdf.pdfs', to: 'users#get_feedbacks_to_do_pdf', as: 'get_feedbacks_to_do_pdf'
      get ':id/get_charts_data', to: 'users#get_charts_data', as: 'get_charts_data'
      get 'get_scores', to: 'users#get_scores', as: 'get_scores'
      get 'get_images', to: 'users#get_images', as: 'get_images'
      get 'archive/:id', to: 'users#archive', as: 'archive'
      get 'restore/:id', to: 'users#restore', as: 'restore'

    end
  end

  resources :plannings do
    collection do
      post 'new/:p_id/:u_id', to: 'plannings#new', as: 'new'
      post 'assign/:p_id/:u_id/a_id', to: 'plannings#assign', as: 'assign'
      post 'dissociate/:a_id/:p_id/:u_id', to: 'activities#dissociate', as: 'dissociate'
      post 'destroy_all_schedules/:p_id', to: 'plannings#destroy_all_schedules', as: 'destroy_all_schedules'
    end
  end

  resources :schedules

  resources :questions do
    collection do
      get 'new/planning_id', to: 'questions#new', as: 'new'
    end
  end

  # pdfs
  get '/pdfs/user_plans_pdf', to: 'pdfs#user_plans_pdf', as: 'user_plans_pdf'

  get 'profile/index'
  # get 'static_pages/help'
  # get 'static_pages/about'

  devise_for :coach_users #, :controllers => {sessions: 'sessions'}
  get 'home/index'
  root 'home#index'

  resources :coach_users do
    collection do
      get 'coach_users/:id', to: 'coach_users#show', as: 'show'
    end
  end



  # Webhooks
  post '/webhooks/telegram_vbc43edbf1614a075954dvd4bfab34l1' => 'webhooks#callback'

	# Wearable devices
	# Actions reserved for the coach:
	get 'wearables', to: 'wearables#index', as: 'wearables'
	get 'wearables/:id', to: 'wearables#show', as: 'show_wearable'
	get 'wearables/:id/monthly_report', to: 'wearables#monthly_report', as: 'monthly_report'
	get 'wearables/:id/weekly_chart', to: 'wearables#weekly_chart', as: 'weekly_chart'
	get 'wearables/:id/monthly_chart', to: 'wearables#monthly_chart', as: 'monthly_chart'
	get 'wearables/:id/edit', to: 'wearables#edit', as: 'edit_wearable'
	post 'wearables/:id/invite', to: 'wearables#invite', as: 'wearable_invite'
	post 'wearables/:id/disable', to: 'wearables#disable', as: 'wearable_disable'
	# Actions reserved for the user
	# starts fitbit oauth2 procedure
	get 'wearables/fitbit/connect/:token', to: 'wearables#connect', as: 'wearables_fitbit_connect'
	# oauth2 callback
	get 'users/auth/fitbit/callback', to: 'wearables#oauth2_callback'

	# User's objectives
	get 'objectives', to: 'objectives#index', as: 'objectives'
	get 'objectives/:id', to: 'objectives#show', as: 'user_objectives'
	get 'objectives/:id/new', to: 'objectives#new', as: 'new_user_objective'
	post 'objectives/:id/create', to: 'objectives#create', as: 'create_user_objective'
	get 'objectives/details/:id', to: 'objectives#details', as: 'objective_details'

  match "/404", :to => "errors#not_found", :via => :all
  match "/500", :to => "errors#internal_server_error", :via => :all


end

app/models/planning.rb
class Planning < ApplicationRecord
  belongs_to :plan
  belongs_to :activity
  has_many :schedules, dependent: :destroy, inverse_of: :planning
  has_many :notifications, dependent: :destroy
  has_many :questions, dependent: :destroy

  accepts_nested_attributes_for :schedules,
                                :allow_destroy => true,
                                :reject_if     => :all_blank

  validates :activity, uniqueness: { scope: :plan, message: 'Un piano non puo\' contenere la stessa attivita\' due volte.' }
  end

app/controllers/plannings_controller.rb
class PlanningsController < ApplicationController

  layout 'profile'

  def new
    @activity = Activity.new
    @plan_id = params[:p_id]
    @user_id = params[:u_id]
  end

  def assign
    @activities = Activity.all
    @plan_id = params[:p_id]
    @user_id = params[:u_id]
  end

  def create
    activity = get_or_create_activity params
    planning = Planning.new(:activity_id =>activity.id, :plan_id => params[:p_id])
    unless activity.id.nil?
      if planning.save
        if completeness_question(planning)
          flash[:OK] = 'Attivita creata/assegnata con successo!'
        else
          flash[:err] = 'C\'e\' stato un problema durante la creazione delle domande di verifica. Ci scusiamo e la invitiamo a riprovare piu\' tardi!'
          flash[:errors] = planning.errors.messages
        end
      else
        flash[:err] = 'C\'e\' stato un problema durante l\'assegnamento dell\'attivit\a\'. Ci scusiamo e la invitiamo a riprovare piu\' tardi!'
        flash[:errors] = planning.errors.messages
      end
    end
    redirect_to plans_users_path(User.find(params[:u_id]))
  end

  def edit
    @planning = Planning.find(params[:id])
    @plan_id = @planning.plan.id
  end

  def update
    planning = Planning.find (params[:id])
    if planning.update (allowed_params)
      flash[:OK] = 'Pianificazione inserita con successo!'
    else
      flash[:err] = "La pianificazione non e' stata inserita!"
      flash[:errors] = planning.errors.messages
    end
    redirect_to plans_users_path(planning.plan.user)
  end

  def destroy
    planning = Planning.find(params[:id])
    if planning.destroy
      flash[:OK] = 'La tua attivita\' e\' stata rimossa dal piano con successo!'
    else
      flash[:err] = 'C\'e\' stato un problema durante la rimozione dell\'attivit\a\' dal piano.'
      flash[:errors] = planning.errors.messages
    end
    redirect_back fallback_location: root_path
  end

  def destroy_all_schedules
    planning = Planning.find(params[:p_id])
    planning.schedules.delete_all
    redirect_back fallback_location: root_path
  end

  private

    def activity_params
      params.require(:activity).permit(:name, :desc, :a_type, :category, :n_times)
    end

    def allowed_params
      params.require(:planning).permit!
    end


  def get_or_create_activity(params)
    if params['new'].nil?
      Activity.find(params['a_id'])
    else
      activity = Activity.new(params.require(:activity).permit(:name, :desc, :a_type, :category, :n_times))
      activity.coach_user = current_coach_user
      unless activity.save
        flash[:err] = 'C\'é stato un problema durante la creazione dell\'attivitá. Ci scusiamo e la invitiamo a riprovare più tardi!'
        flash[:errors] = activity.errors.messages
      end
      activity
    end
  end

  def completeness_question(planning)
    question = Question.new text: "Hai portato a termine l'attività  📌[#{planning.activity.name}] ?", q_type: 'completeness'
    question.planning = planning
    if question.save
      answer1 = Answer.new text: 'Si'
      answer2 = Answer.new text: 'No'
      answer1.question = question
      answer2.question = question
      answer1.save && answer2.save ? true : false
    end
  end
end

app/helpers/plannings_helper.rb
require 'date'

module PlanningsHelper
  def setup_planning(planning)
    unless planning.schedules.any?
      planning.activity.n_times.times do
        planning.schedules.build
      end
    end
    planning
  end

  def time_format(datetime)
    datetime.strftime('%H:%M') unless datetime.blank?
  end

  def date_format(datetime)
    datetime.strftime('%m/%d/%Y') unless datetime.blank?
  end


  module DateTimeMixin

    def next_week
      self + (7 - self.wday)
    end

    def next_wday (n)
      n > self.wday ? self + (n - self.wday) : self.next_week.next_day(n)
    end

  end


end

app/views/plannings/_assign.html.erb
<div class="col-lg-12 col-lg-offset-4" id="activity-insert-card-wide">
  <div class="card" id="assign_table">
    <div class="card-header" data-background-color="purple">
      <h4 class="title">Scegli un'attività gia presente nel sistema</h4>
      <p class="category"></p>
    </div>
    <div class="card-content table-responsive">
      <table class="table table-hover content_align">
        <thead class="text-warning">
        <th>Nome</th>
        <th>Categoria</th>
        <th>Modifica</th>
        <th>Assegna</th>
        </thead>
        <tbody>

        <% @activities.each do |a| %>
          <tr>
            <td><%= a.name %> </td>
            <td><%= match_category(a.category) %></td>
            <td><%= link_to 'Modifica', activity_path(a), class: 'btn btn-primary btn-sm' %></td>
            <td><%= link_to 'Assegna', plannings_path(:a_id => a.id, :p_id => @plan_id, :u_id => @user_id),
                            method: 'post', class: 'btn btn-success btn-sm' %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/plannings/_edit.html.erb
<div class="col-lg-12 col-lg-offset-8" id="activity-insert-card-wide">
  <div class="card" id="assign_table">
    <div class="card-header" data-background-color="purple">
      <h4 class="title">Nuove pianificazioni per l'attività</h4>
      <p class="category"></p>
    </div>
    <div class="card-content table-responsive">
      <% case @planning.activity.a_type %>
      <% when '0' %>

        <%= form_for setup_planning(@planning) do |f| %>
          <div>Devi inserire esattamente <%= @planning.activity.n_times %> orari visto che si tratta di un'attività GIORNALIERA<br>
            da fare esattmante  <%= @planning.activity.n_times %>/GIORNO </div>

          <%= f.fields_for :schedules do |ff| %>
            <div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= ff.text_field :time, class: 'daily-input mdl-textfield__input', :as => :string, :value => time_format(ff.object.time), pattern: '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$', 'data-daily' => true %>
                <%= ff.label :time, 'Ora', class: 'mdl-textfield__label' %>
                <span class="mdl-textfield__error">Ora nel formato 24h e HH:mm</span>
              </div>
            </div>
          <% end %>

          <div>
            <%= link_to do %>
              <button id="monthly-submit" type="submit" class="btn btn-info btn-large mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect">
                <i class="material-icons">alarm_add</i>&nbsp Aggiungi pianificazione all'attività
              </button>
            <% end %>
          </div>
        <% end %>

      <% when '1' %>

        <%= form_for setup_planning(@planning) do |form| %>
          <% days_of_week = [['', ''], ['Lunedi', 0], ['Martedi', 1],['Mercoledi', 2],
                             ['Giovedi', 3],['Venerdi', 4],['Sabato', 5],['Domenica', 6]] %>

          <br>Devi inserire esattamante <%= @planning.activity.n_times %> ORARI di tipo GIORNO, visto che l'attività <br>
          presa in considerazione è un'attività SETTIMANALE da fare <%= @planning.activity.n_times %>/SETTIMANA. <br>

          <%= form.fields_for :schedules do |f| %>
            <div>
              <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label">
                <%= f.select :day, options_for_select(days_of_week, f.object.day), {}, {class: 'mdl-selectfield__select'} %>
                <div class="mdl-selectfield__icon"><i class="material-icons">arrow_drop_down</i></div>
                <label class="mdl-selectfield__label" for="professsion">Giorno</label>
              </div>

              <div class="time-sched mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                <%= f.text_field :time, class: 'mdl-textfield__input', :as => :string, :value => time_format(f.object.time),
                                 pattern: '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$' %>
                <%= f.label :time, 'Ora', class: 'mdl-textfield__label' %>
                <span class="mdl-textfield__error">Ora nel formato 24h e HH:mm</span>
              </div>

            </div>
          <% end %>
          <br><br>
          <div>
            <button id="add-hour-btn" class="add-hour mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" >
              <i class="material-icons">alarm_add</i> &nbsp Aggiungi Ora
            </button>
          </div>
          <br><br>
          <div>
            <%= link_to do %>
              <button id="monthly-submit" type="submit" class="btn btn-info btn-large mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect">
                <i class="material-icons">alarm_add</i>&nbsp Aggiungi pianificazione all'attività
              </button>
            <% end %>
          </div>

        <% end %>

      <% else %>

        <br>
        <div class="weekly-schedules-forms">

          <%= form_for setup_planning(@planning) do |form| %>
            <br>Devi inserire esattamante <%= @planning.activity.n_times %> ORARI di tipo DATA, visto che l'attività <br>
            presa in considerazione e' un'attività MENSILE da fare <%= @planning.activity.n_times %>/MESE. <br>

            <%= form.fields_for :schedules do |f| %>
              <div>
                <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  <%= f.text_field :date, class: 'mdl-textfield__input monthly-schedule-date', :as => :string, :value => date_format(f.object.date),

                                   pattern: '^(?:(?:31(\/|-|\.)(?:0?[13578]|1[02]))\1|(?:(?:29|30)(\/|-|\.)(?:0?[1,3-9]|1[0-2])\2))(?:(?:1[6-9]|[2-9]\d)?\d{2})$|^(?:29(\/|-|\.)0?2\3(?:(?:(?:1[6-9]|[2-9]\d)?(?:0[48]|[2468][048]|[13579][26])|(?:(?:16|[2468][048]|[3579][26])00))))$|^(?:0?[1-9]|1\d|2[0-8])(\/|-|\.)(?:(?:0?[1-9])|(?:1[0-2]))\4(?:(?:1[6-9]|[2-9]\d)?\d{2})$' %>
                  <%= f.label :date, 'Data', class: 'mdl-textfield__label' %>
                  <span class="mdl-textfield__error">Data nella forma GG/MM/AAAA oppure GG.MM.AAA oppure GG-MM-AAAA</span>
                </div>

                <div class="time-sched mdl-textfield mdl-js-textfield mdl-textfield--floating-label">
                  <%= f.text_field :time, class: 'mdl-textfield__input',  :as => :string, :value => time_format(f.object.time),
                                   pattern: '^([0-9]|0[0-9]|1[0-9]|2[0-3]):[0-5][0-9]$' %>
                  <%= f.label :time, 'Ora', class: 'mdl-textfield__label' %>
                  <span class="mdl-textfield__error">Ora nel formato 24h e HH:mm</span>
                </div>


              </div>

            <% end %>
            <br><br>

            <div>
              <button id="add-hour-btn" class="add-hour mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect" type="submit">
                <i class="material-icons">alarm_add</i> &nbsp Aggiungi Ora
              </button>
            </div>
            <br><br>
            <div>



              <%= link_to do %>
                <button id="monthly-submit" type="submit" class="btn btn-info btn-large mdl-button mdl-js-button mdl-button--raised mdl-button--colored mdl-js-ripple-effect">
                  <i class="material-icons">alarm_add</i>&nbsp Aggiungi pianificazione all'attività
                </button>
              <% end %>
            </div>

          <% end %>

        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/plannings/_new.html.erb
 



<div class="content">
  <div class="container-fluid">
    <div class="row">
      <div class="col-lg-12 col-lg-offset-8">
        <div class="card">
          <div class="card-header" data-background-color="green">
            <h4 class="title">Inserisci i dati di una nuova attivita</h4>
            <p class="category">*Tutti i campi sono obbligatori!</p>
          </div>
          <div class="card-content">
            <div class="insert-error-msg"><%= yield(:insert_error_msg) %></div>



            <%= form_for @activity, url: plannings_path(:new => true, :p_id => @plan_id,
                                                        :u_id => @user_id), method: 'post' do |f| %>
              <%= f.hidden_field :id%>

              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ">
                <%= f.label :name, 'Nome Attività', class: 'mdl-textfield__label' %>
                <%= f.text_field :name, class: 'mdl-textfield__input' %>
              </div>


              <div class="activity-type">
                <% a_types = [['', ''],['Giornaliera', 0], ['Settimanale', 1], ['Mensile', 2]]%>

                <div>
                  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label">
                    <%= f.select :a_type, options_for_select(a_types), {}, {class: 'mdl-selectfield__select'} %>
                    <div class="mdl-selectfield__icon"><i class="material-icons">arrow_drop_down</i></div>
                    <label class="mdl-selectfield__label">Tipologia Attività</label>
                  </div>
                </div>
              </div>


              <div id="volte-con-es" class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label ">
                <%= f.label :n_times, 'Volte per Tipologia (Es. 2 = 2 volte a settimana se tipologia e settimanale)', class: 'mdl-textfield__label' %>
                <%= f.text_field :n_times, class: 'mdl-textfield__input', type: 'number' %>
              </div>

              <div class="category">
                <% categories = [['', ''], ['Dieta', 0], ['Attivita Fisica', 1], ['Benessere Mentale', 2], ['Medicina', 3], ['Altro', 4]]%>

                <div>
                  <div class="mdl-selectfield mdl-js-selectfield mdl-selectfield--floating-label">
                    <%= f.select :category, options_for_select(categories), {}, {class: 'mdl-selectfield__select'} %>
                    <div class="mdl-selectfield__icon"><i class="material-icons">arrow_drop_down</i></div>
                    <label class="mdl-selectfield__label">Categoria Attività</label>
                  </div>
                </div>

              </div>


              <div class="activity-desc-container mdl-textfield mdl-js-textfield mdl-textfield--floating-label" >
                <%= f.label :desc, 'Descrizione', class: 'mdl-textfield__label' %>
                <%= f.text_area :desc, class: 'mdl-textfield__input activity-desc' %>
              </div>



              <div>
                <button type="submit" class="btn btn-primary btn-large pull-right">
                  <i class="material-icons">add</i> &nbsp Salva Attività</button>
              </div>

            <% end %>

            <div class="clearfix"></div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/plannings/assign.js.erb
$('document').ready(function() {
    $('#lateral-panel-<%= @plan_id %>').empty().html("<%= escape_javascript(render 'plannings/assign') %>")
});

app/views/plannings/edit.js.erb
$('document').ready(function() {
    $('#lateral-panel-<%= @plan_id %>').empty().html("<%= escape_javascript(render 'plannings/edit') %>");

    check_daily_blank();

    $('.daily-input').change(function(e) {
        e.preventDefault();
        return check_daily_blank();
    });

    $('.monthly-schedule-date').datepicker({
        format: 'dd/mm/yy'
    });

    $('.add-hour').click(function(e) {
        e.preventDefault();
        return show_hide_hour();
    });

    // adds is-focused class to the label in order to make a floating label
    $('.mdl-textfield__input').parent().addClass('is-focused');
    $('.mdl-selectfield__select').parent().addClass('is-focused');

});

app/views/plannings/new.js.erb
$('document').ready(function() {
    $('#lateral-panel-<%= @plan_id %>').empty().html("<%= escape_javascript(render 'plannings/new') %>")

    $('.mdl-textfield__input').parent().addClass('is-focused');
    $('.mdl-selectfield__select').parent().addClass('is-focused');
});